### ISSUE TITLE
Built-in animations of "Animate CSS" aren't working in version 6.

### ISSUE THREAD

**Issue by saifullahamin** [wellyshen/use-web-animations#255]
Recently I was working on a project. I had installed version 0.6 and there was an error that "bounce is not exported from @wellyshen/use-web-animations". Then I installed version 0.5.11  and it was working then.

Hope my issue will be helpful in solving the problem.

**Comment by wellyshen** [comment]
@saifullahamin Thank you for reporting this issue, it has been fixed in the [latest version](https://github.com/wellyshen/use-web-animations/releases/tag/v0.6.1).
