### ISSUE TITLE
The hook die when I try to use 'onFinish' property function

### ISSUE THREAD

**Issue by nicolasleal570** [wellyshen/use-web-animations#31]
# Bug Report

## Describe the Bug

I'm try to make a sidebar slider and I need to know when is the animation finished. I'm using the property 'onFinish' and the browser trown an error saying 'Can't read property then of undefined'. I'm using next.js by the way.
Your library is awesome!

## Screenshots

![image](https://user-images.githubusercontent.com/38839484/86428577-16769d80-bcbb-11ea-9f9a-d913f5ad49a5.png)

**Comment by wellyshen** [comment]
@nicolasleal570 Thank you for reporting this bug, it should be fixed in the latest version. BTW, some browsers don't support the `onFinished` event yet, however you can [use onUpdate event to monitor the animation's state instead]https://github.com/wellyshen/use-web-animations#basic-usage).
