### ISSUE TITLE
onFinish is only called after first finishing an animation

### ISSUE THREAD

**Issue by DamianPereira** [wellyshen/use-web-animations#469]
# Bug Report

## Describe the Bug

I'm trying to use the onFinish callback, together with controlling play status. After the animation finishes for the first time, the onFinish callback will be called, but not on subsequent calls.

## How to Reproduce

Add an onFinish handler, start the animation with getAnimation().play() twice.

## CodeSandbox Link

[Bug example](https://codesandbox.io/s/use-web-animations-onfinish-bug-icbjs?file=/src/App.js).

## Expected Behavior

onFinish should be called whenever playState switches from 'running' to 'finished'

## Your Environment

- Device: Lenovo thinkpad
- OS: Manjaro Linux
- Browser: Both Chrome and Firefox tested.
- Version: Both 0.9, and 0.7.4 show this behavior. I have not tested 0.8, should

**Comment by DamianPereira** [comment]
The same codesandbox shows another issue, which I do not see in the real app code, but only in this sandbox. autoplay: false seems to be ignored. Should I open a different issue for this?

**Comment by wellyshen** [comment]
@DamianPereira Thank you for reporting this issue, will investigate it soon.

**Comment by wellyshen** [comment]
@DamianPereira It should be fixed in [v0.9.1](https://github.com/wellyshen/use-web-animations/releases/tag/v0.9.1)

**Comment by DamianPereira** [comment]
Thanks a lot for the quick response!
