### ISSUE TITLE
Typescript types don't include animation presets

### ISSUE THREAD

**Issue by nicholaschiang** [wellyshen/use-web-animations#62]
# Bug Report

## Describe the Bug

The Typescript types in `index.d.ts` don't define the huge list of (incredibly useful) preset animations. For example, when importing the `fadeOut` preset:

```typescript
import useWebAnimations, { fadeOut } from '@wellyshen/use-web-animations';
```
I get the following error (even though `fadeOut` *is* exported by `index.js`... it's just not defined in `index.d.ts` so Typescript doesn't pick it up):
```
Module '"@wellyshen/use-web-animations"' has no exported member 'fadeOut'. Did you mean to use 'import fadeOut from "@wellyshen/use-web-animations"' instead?
```

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a Typescript project and import an animation preset.
2. Try to compile (or just run ESLint).
3. See error.

## Expected Behavior

To fix this, merely add all of those animation presets as exported constants to your `index.d.ts` (this will be quite tedious... you should probably look into a better way to do this perhaps).

**Comment by wellyshen** [comment]
@nicholaschiang Thank you for reporting this bug. It should be fixed via the [v0.5.2](https://github.com/wellyshen/use-web-animations/releases/tag/v0.5.2)
